### ISSUE TITLE
babel-plugin-react-error-catcher

### ISSUE THREAD

**Issue by timbur** [KeywordBrain/redbox-react#1]
Nice work with `redbox-react` so far.  :)

Funny timing though.  This has been on my todo list for a while and literally the day after you create `redbox-react`, I start working on [`babel-plugin-react-error-catcher`](https://github.com/loggur/babel-plugin-react-error-catcher).  I had actually considered building on top of `redbox-react` for my use-cases but decided it would be easier to just make a Babel plugin.

No idea which direction you're headed with this repo, and I am definitely not trying to steal your thunder or anything!  But I figure I should probably let you know about what I've put together and maybe we could put forth some kind of collective effort and/or pull code from each other's repos or something.  :)

**Comment by davidpfahler** [comment]
@timbur Great to see that many people are working on dev tools any making the dev experience better. I will clarify the goal of this project / repo in the Readme, but the short version on top of my head is:

## What this project does
`redbox-react` is a UI React Component that renders an error and it's stack using StackFrames in a big red box. There might be customisations to the look of it coming in the future.

## What this project does not
`redbox-react` will not catch errors for you. It does not dictate or care where in your code and how you catch an error.

## Where will this project be useful?
Of course, feel free to use it how and where ever you like. One thing I'm personally trying to push is optional error catching in the react-hot-loader currently discussed [here](https://github.com/gaearon/react-hot-loader/issues/164#issuecomment-123270225). `redbox-react` may be used to render an error caught  by the hot loader.

**Comment by davidpfahler** [comment]
@timbur I just realised we might work together on this quite effectively. Do you think it would be possible to make your babel plugin configurable as to what error component it renders? If so, your babel plugin is the decorator to wrap a component's render function, but my (and any other people's) component actually decides how do render the error. Does that sound reasonable?

Please check out the [discussion on react-hot-loader](https://github.com/gaearon/react-hot-loader/issues/164#issuecomment-123270225). I think this is exactly what @syranide is asking for there.

**Comment by timbur** [comment]
> If so, your babel plugin is the decorator to wrap a component's render function, but my (and any other people's) component actually decides how do render the error. Does that sound reasonable?

Yeah that sounds perfect!  Thanks for the clarification on what `redbox-react` is for.  I definitely misunderstood the intent.  Our modules will work really well together.  :)

**Comment by timbur** [comment]
@davidpfahler Did you get a chance to try passing `redbox-react` to [`babel-plugin-react-error-catcher`](https://github.com/loggur/babel-plugin-react-error-catcher)?  I actually haven't gotten around to it yet myself but it should work in theory, assuming `redbox-react` expects an `error` prop.  :)

**Comment by davidpfahler** [comment]
@timbur I'm trying, but can't figure out why [this example](https://github.com/KeywordBrain/redbox-react/tree/master/examples/babel-plugin-react-hot) wouldn't work. Maybe you can take a moment and look into it. I'm pretty sure it's a minor mistake.

**Comment by timbur** [comment]
Awesome!  Works beautifully.

I did have some strange issue where my PC was refusing port 3000 for the socket connection, so I removed `'webpack-dev-server/client?http://localhost:3000'` from `webpack.config.js` and it worked just fine.  It's most likely an issue with my firewall or something though and not your particular config.

> For your interest, I'm planning to add props to the component that allow you to specify the behavior. For example, whether the component should fill the entire screen or just the space of the component it is replacing, etc.

Sounds good!  If there's anything I can do to make that easier for you to integrate, let me know.  The `rendered` function export should hopefully be all you need for any customization based on the target component.  Check [`same-size-reporter`](https://github.com/loggur/babel-plugin-react-error-catcher/blob/master/reporters/same-size-reporter.js) for reference if you haven't already.  :)
