### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by trevordmiller** [KeywordBrain/redbox-react#11]
When using the setup recommended in [react-transform-boilerplate](https://github.com/gaearon/react-transform-boilerplate) by @gaearon, the `.babelrc` requires in `redbox-react` which causes an error because `window` doesn't exist in Node:

```
> mocha ./src/**/*.test.js --compilers js:babel/register

/Users/trevordmiller/projects/playground/nexus/node_modules/redbox-react/dist/redbox.js:504
			return /msie [6-9]\b/.test(window.navigator.userAgent.toLowerCase());
			                           ^
ReferenceError: window is not defined
```

It would be cool to have a environment check so that this error isn't thrown when the package is `require` or `import`ed.

**Comment by trevordmiller** [comment]
Also, discussion around this issue has been happening in the `react-transform` channel in the `reactiflux` Slack team: https://reactiflux.slack.com/

**Comment by gaearon** [comment]
(Just FYI—while this is being fixed, you can easily use any other component for error reporting, including a custom one. It's configurable in `.babelrc`.)

**Comment by mathieumg** [comment]
> It would be cool to have a environment check so that this error isn't thrown when the package is require or imported.

:+1:

> you can easily use any other component for error reporting

@aulizko has done https://github.com/aulizko/delicate-error-reporter in the meantime :)

**Comment by trevordmiller** [comment]
@mathieumg Yeah, I switched to @aulizko's package and it has worked well running from both the server and client since it has an environment check. The unobtrusive errors are a plus as well :)

**Comment by gaearon** [comment]
Anybody wants to make a PR for this?

**Comment by aulizko** [comment]
@gaearon I'm working on PR fixing this right now ;)

**Comment by gaearon** [comment]
:+1:

**Comment by gaearon** [comment]
:+1:

**Comment by davidpfahler** [comment]
@aulizko Big, big thank you for your contribution. I [pushed to master](https://github.com/KeywordBrain/redbox-react/commit/79e674daa06998954729e85cde96d14a383cc11e). New version will be out any second thanks to [semantic-release](https://github.com/semantic-release/semantic-release).
