### ISSUE TITLE
Update/remove peerDep

### ISSUE THREAD

**Issue by STRML** [KeywordBrain/redbox-react#14]
Now that 0.14.0-rc1 is out, the peerDep fails.

**Comment by davidpfahler** [comment]
@STRML What exactly is the problem with peerDependencies for you? What fails?

**Comment by STRML** [comment]
This change fixed it: https://github.com/KeywordBrain/redbox-react/commit/79e674daa06998954729e85cde96d14a383cc11e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L54

**Comment by davidpfahler** [comment]
@STRML OK, nice.
