### ISSUE TITLE
Why the component is fixed

### ISSUE THREAD

**Issue by brenoc** [KeywordBrain/redbox-react#22]
I wonder why the component rendered has its CSS "position" as "fixed" taking the whole page. Don't you think would be better if it just covered the component with the issues?

I removed the fixed value of the CSS and it was really nice to see just the component with the error with the redbox:
![redbox](https://cloud.githubusercontent.com/assets/284515/9918995/886b3d72-5ca0-11e5-89fb-e31e6daea137.png)

**Comment by gaearon** [comment]
I think one of the reasons is that it's too easy to miss a failing component that's offscreen or too small, which would blow up in production. If you'd like less obtrusive error reporting check out [delicate-error-reporter](https://github.com/aulizko/delicate-error-reporter).

**Comment by davidpfahler** [comment]
@brenoc Thanks for the suggestion. As @gaearon said, it very much depends on how your app works and what kind of component you have. It's also simply a matter of taste. I talked to @aulizko a couple of days ago and we agreed that it would be best if there were a way to configure the error reporter without having to create a completely new component (like delicate-error-reporter) for every tiny change you would like to have (like position fixed or not). We are going to try to push in that direction.
