### ISSUE TITLE
Mount onto document.body

### ISSUE THREAD

**Issue by nickcolley** [KeywordBrain/redbox-react#27]
I have instances where my fixed header is above the redbox, maybe we could render it outside of it's current parent so this never happens?

**Comment by mxlje** [comment]
Could you provide a reproducible example for this? Thank you.

**Comment by cpsubrian** [comment]
I'm guessing @nickcolley either has some relative positioning in his hierarchy, which is causing redbox's zIndex to only be 'relatively' high (at 9999). I'm having a similar issue where my redboxes are not 'fixed' to the viewport, they are fixed inside of relatively positioned parents. IMO redbox is a perfect candidate to be a so-called 'portal' and append itself to body, so its always fixed position relative to the viewport and its zIndex of 9999 should usually be plenty high enough to be on top of everything.

![screenshot 2015-10-16 13 30 10](https://cloud.githubusercontent.com/assets/319152/10552662/34077666-740a-11e5-9def-6f7f60d759c8.png)

**Comment by cpsubrian** [comment]
Ok so did some investigation as to when fixed positioning isn't really fixed. Here is a jsFiddle that illustrates:

http://jsfiddle.net/12wdw11w/

Basically, if a parent of the fixed positioned element is forced onto its own 'composite layer' (via something like `transform: translate`, then it will be positioned relative that layer.

About composite layers: http://www.html5rocks.com/en/tutorials/speed/layers/

The fix still remains the same, redbox needs to mount to body.

**Comment by cpsubrian** [comment]
Working up a PR for what this would look like.

**Comment by mxlje** [comment]
Thanks @cpsubrian! Looking forward to your PR.

**Comment by nickcolley** [comment]
Thank you @cpsubrian :)

**Comment by davidpfahler** [comment]
See #60
