### ISSUE TITLE
0.14 support?

### ISSUE THREAD

**Issue by clearly** [KeywordBrain/redbox-react#29]
I'm preparing to upgrade to react 0.14 from 0.14-rc1. All other components I'm using (react-router, react-bootstrap, etc...) have all upgrade to 0.14. Redbox is the last one. Any idea if/when it would be upgraded?

**Comment by davidpfahler** [comment]
@clearly From a quick look at things, it seems like 0.14 breaks redbox. I have very little time atm, but I'd be happy to do review a PR.

**Comment by katraoui** [comment]
+1

**Comment by eelcocramer** [comment]
@davidpfahler you say 0.14 breaks redbox but it seems to build and run tests fine on top of 0.14.

How does 0.14 breaks redbox?

**Comment by dzannotti** [comment]
confirmed working on 0.14

**Comment by davidpfahler** [comment]
@eelcocramer @dzannotti when I run the examples, they don't work for me anymore. Did you run the examples?

**Comment by dzannotti** [comment]
@davidpfahler nope, i'm using it in production right now and recently upgraded react and redbox and react-transform-hmr and all worked out of the box first time

**Comment by eelcocramer** [comment]
I ran the tests. Just tried the examples `react-hot-loader-example` runs fine, `react-transform-catch-errors` has an error (not sure it is related to react) and I'm not sure how to run the 3rd example.

**Comment by okonet** [comment]
I see `The package react does not satisfy its siblings' peerDependencies requirements!` when installing this or other packages.

**Comment by davidpfahler** [comment]
Hi everyone, it's been a while and i just wanted to say I'd still be very glad if someone your provide a PR for this showing that tests and examples still worked. I will get back to this asap, but right now time is very constrained for me.

**Comment by eelcocramer** [comment]
No much time either but I put a quick pull request together of the clone I ran the tests and examples in as discussed above.

**Comment by gaearon** [comment]
The component works fine with React 0.14.
Examples need updating but let’s continue that discussion in #43.
