### ISSUE TITLE
Release to npm and github using semantic-release

### ISSUE THREAD

**Issue by davidpfahler** [KeywordBrain/redbox-react#3]
Before I set up [semantic-release](https://github.com/semantic-release/semantic-release), I want to make sure I have the npm workflow set up correctly, for example, what scripts need to run before publishing, so that the `dist` and `src` folders are both on npm.

Should the examples be on npm, too?

Anything else I need to change before publishing to npm?

Feedback / help is much appreciated.

/cc @boennemann

**Comment by boennemann** [comment]
You should remove tests and linting from prepublish, so it only builds the assets you want.
You then set up .gitignore and .npmignore as you need (lmk if you need more info on that).

From then on it's `semantic-release-cli setup`

**Comment by davidpfahler** [comment]
@boennemann Thanks! I'd be very grateful for quick sanity check of the latest [`.gitignore`](https://github.com/KeywordBrain/redbox-react/blob/0313db0cff043f4775b88a76ecfc6313eec622a5/.gitignore) and [`.npmignore`](https://github.com/KeywordBrain/redbox-react/blob/0313db0cff043f4775b88a76ecfc6313eec622a5/.npmignore). Then, I'll have the pleasure of using the cli for the first time :grinning:.

**Comment by boennemann** [comment]
https://github.com/KeywordBrain/redbox-react/pull/5

When using the CLI let it overwrite your .travis.yml. Single node.js version should suffice. :+1:
