### ISSUE TITLE
The box covers the whole page thus making it harder to figure out which component crashed and what exactly is wrong.

### ISSUE THREAD

**Issue by mik01aj** [KeywordBrain/redbox-react#32]
And any subsequent errors show their own boxes on top of each other. So it's hard to uncover the page.

![image](https://cloud.githubusercontent.com/assets/3027415/11060490/eba0fb9a-87a0-11e5-81af-e5ab45abb376.png)

**Comment by davidpfahler** [comment]
Hi @mik01aj! Thanks for reporting your issues with redbox. I get that it's non-sensical that multiple errors stack multiple redbox instances on top of each other. That might be considered a bug, although I'm not sure it's one we can really solve in redbox. Please remember that redbox is just supposed to display an error and nothing more.

Regarding your second issue that redbox fills the entire screen and you dislike that, please note that all style attributes of redbox can be overwritten via `props.style`. See [style.js](https://github.com/KeywordBrain/redbox-react/blob/ade40b163a8bc210ade04fb4f52e42815f4c2c09/src/style.js) for more details, as well as [this line](https://github.com/KeywordBrain/redbox-react/blob/6b44f19fd47242eafd297c9259addd21df72eae9/src/index.js#L22).

This is unfortunately not documented, yet. I would welcome a PR that changes that.

**Comment by gaearon** [comment]
I'm closing as this doesn't appear very actionable. Redbox is an opinionated module; you can make a different one if you'd like. For example you can use https://github.com/aulizko/delicate-error-reporter.
