### ISSUE TITLE
How to pass props to redbox-react from react-transform-catch-errors?

### ISSUE THREAD

**Issue by cbenz** [KeywordBrain/redbox-react#41]
In the README I can read:

> If using react-transform-catch-errors you can add these options to your .babelrc through the imports property.

But when I look at the react-transform-catch-errors README in the "installation" section, I don't find any information about how to pass props to the imported redbox-react module.

Any hint before I dive in the source? :)

**Comment by gaearon** [comment]
Yep, see here: https://github.com/gaearon/babel-plugin-react-transform/pull/28#issuecomment-144536185. I added a link to that comment from `react-transform-catch-errors` README. The options file itself should just export the props you want.

**Comment by cbenz** [comment]
Thanks, very clear now!
