### ISSUE TITLE
Handle non-Error error values?

### ISSUE THREAD

**Issue by markerikson** [KeywordBrain/redbox-react#51]
I'm using the Cesium 3D globe library, which can throw its own error class called a DeveloperError.  Redbox is failing when it's given one of those, and I see that it's expecting `error: PropTypes.instanceOf(Error).isRequired`, which apparently DeveloperError doesn't fit.

Is there a suggested way to handle alternative error types?

**Comment by davidpfahler** [comment]
Thanks for reporting your issue, @markerikson. This is a tricky one. I very much understand your problem and it is definitely something that happens in "the real world". On the other hand, I'd like to keep redbox as simple as possible and I like to use React's PropTypes feature.

To be frank, Cesium 3D is (probably) at fault here, as I can't imagine why they can't base their `DeveloperError` on the `Error` "class". May I ask you to open an issue with them? If that bears no fruit, I'd be happy to reconsider a solution here and will reopen this issue, but I'd like to keep this as kludge-free as possible.

**Comment by markerikson** [comment]
Huh.  So I actually just went to double-check the Cesium source code, and it appears that they just updated DeveloperError to extend Error a month ago: https://github.com/AnalyticalGraphicsInc/cesium/commit/a02134921627d5d66a28d1d25dd73e76d2d24a8c .  That should presumably resolve things overall (and I personally will just need to update my Cesium package).

Thanks!

**Comment by davidpfahler** [comment]
@markerikson You are most welcome. Thanks for your nice comment. It always makes me happy to see people who appreciate open source work.
