### ISSUE TITLE
Include sourcemaps in your build

### ISSUE THREAD

**Issue by gajus** [KeywordBrain/redbox-react#53]
Your `./dist` files are missing source maps. Makes it impossible to debug errors.

```
$ tree ./node_modules/redbox-react
./node_modules/redbox-react
├── CHANGELOG.md
├── LICENSE.md
├── README.md
├── dist
│   ├── redbox.js
│   └── redbox.min.js
├── lib
│   ├── index.js
│   ├── lib.js
│   └── style.js
├── package.json
└── src
    ├── index.js
    ├── lib.js
    ├── redbox.css
    └── style.js
```

**Comment by davidpfahler** [comment]
Yes, optional source maps would be great. I'm not up-to-date on how the cool kids do that these days. We [wanted to update to Babel 6](https://github.com/KeywordBrain/redbox-react/pull/42) for some time. We should probably tie the two together (or not?). I'd welcome a PR, as I can't say when I will have time to fix this myself.

**Comment by FredyC** [comment]
@gajus Can you elaborate more please why do you need source maps for this module exactly? Is it for production debugging or during development of your app? You can as well just use non-minified file for debugging purposes as Babel output is fairly readable for this module.

**Comment by gajus** [comment]
Because when it does break, it produces no readable errors.

I don't remember what was the original issue that I had.

For all personal intents and purposes, I no longer need the source maps. Please re-open if you want to take ownership of the requirement.
