### ISSUE TITLE
Compatibility with the new React Hot Loader?

### ISSUE THREAD

**Issue by joshburgess** [KeywordBrain/redbox-react#58]
It looks like the new react-hot-loader is meant to replace the original as well as react-transform. I know some people are looking to make the move to that as it now supports hot reloading of functional components... Is redbox-react compatible with it? If not, are there any major roadblocks to getting it to work with it?

**Comment by gaearon** [comment]
Sure, it’s compatible, in fact RHL3 uses it internally.

**Comment by joshburgess** [comment]
Okay, cool. Perhaps, the docs should be updated? This line was a bit confusing...

> react-hot-loader (deprecated! see example, relies on changes in unmerged pull request and will not be merged!)

Where would I go to see an example of how redbox-react is configured to hook into RHL3?

**Comment by gaearon** [comment]
It was referring to code in 1.x that got deprecated. 3.x is different but is not stable yet.
