### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by dzannotti** [KeywordBrain/redbox-react#6]
main in package.json points to index.js instead of dist/redbox.js causing issues when importing

**Comment by davidpfahler** [comment]
@dzannotti I was unsure what the best `main` field would be. For example, I'm importing redbox-react in projects of mine where I also use webpack and babel-loader + css-loader setup. Basically I want to allow people to import the source as well as dist, depending on what they need. Can you please explain why you think setting `main` to `dist/redbox.js` is the better alternative?

**Comment by dzannotti** [comment]
In my head it makes it an atomic component.
Specifically in my use case my webpack doesn't have support for css loader (we don't use it) so i can't require from src. Currently to work around this I'm working with a webpack alias from redbox-react to redbox-react/dist/redbox to make it work

**Comment by dzannotti** [comment]
still on package.json would be nice to have 0.14-beta2 as option

**Comment by davidpfahler** [comment]
@dzannotti I reconsidered your request regarding the `main` field. Also, it would be great to have the beta you mentioned. Would I be asking to much from you to make a pull request?
